language: node_js
node_js: '6'
cache: yarn
services:
  - postgresql
before_script:
  - psql -c 'create database hapiapistarter;' -U postgres
  - psql -d hapiapistarter -c 'create schema core authorization postgres' -U postgres
script: npm run test-ci
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
